hot#-------------------------------
# Site Settings
title: cmcnally travel
logo: # You can add own logo. For example '/images/logo.png'.
description: personal blogging for travel
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cmcnally.github.io" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Author Settings
author:
  author__name: Catharine McNally
  author__bio: Curious adventurer. Creative outlet via photography and writing.
  author__avatar: '/images/headshot.JPG'

social:
- {icon: "ion-logo-facebook", link: "https://facebook.com/catharine.mcnally"}
- {icon: "ion-logo-instagram", link: "https://instagram.com/cmcnally"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  hero__title: Hi, I’m Catharine
  hero__description: Curious adventurer. Creative outlet via photography and writing. 
  hero__image: '/images/headshot.JPG'


#-------------------------------
# Gallery Footer Section
gallery:
  gallery__title: Gallery
  gallery__columns: 3
  gallery__images:
    - alt: 'Rest'
      url: '/images/moab-1.jpg'
    - alt: 'Lifestyle'
      url: '/images/moab-2.jpg'
    - alt: 'Hobby'
      url: '/images/moab-3.jpg'
    - alt: 'Notes'
      url: '/images/103.jpg'
    - alt: 'Rest'
      url: '/images/104.jpg'
    - alt: 'Hobby'
      url: '/images/105.jpg'
    - alt: 'Fashion'
      url: '/images/106.jpg'
    - alt: 'Notes'
      url: '/images/107.jpg'
    - alt: 'Rest'
      url: '/images/108.jpg'


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed
